vich_uploader:
    db_driver: orm

    mappings:
        profile_pictures:
            uri_prefix:         /profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'